### ISSUE TITLE
Login error! Connection error!

### ISSUE THREAD

**Issue by Valcansel** [instabot-py/instabot.py#1247]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC Os High Sierra 10.13.4

## Python Version?
3

## Description

Logged me out after a pause and when I try to run the program again!

```
25.04.2018_18:44 Login error! Connection error!
25.04.2018_18:44 Removing already liked medias..
25.04.2018_18:44 Trying to unfollow #1: 
25.04.2018_18:44 Looks like there is nobody to unfollow.
25.04.2018_18:44 Removing already liked medias..
25.04.2018_18:44 Removing already liked medias..
25.04.2018_18:44 Removing already liked medias..
25.04.2018_18:44 Removing already liked medias..
25.04.2018_18:44 Removing already liked medias..
```

**Comment by constantinosbou** [comment]
Same here!

**Comment by srwiseman** [comment]
Anything in your error logs?

**Comment by bkurnaz** [comment]
same here...

**Comment by nigh8w0lf** [comment]
same behaviour as @Valcansel 
The recent terms and conditions update said that they will be collecting scroll and swipe gesture information to detect bots, hope they have not caught up to us already!

**Comment by bkurnaz** [comment]
it doesn't work because your ip address got probably banned from instagram. Use a proxy and your issue should be solved

**Comment by nozimm** [comment]
How I fixed it:
(i use a raspberry pi)
1. boot into desktop environment
2. tried to login in browser (if you use a proxy, use this one alos here)
3. verify the account via email
4. start bot again

**Comment by bradster45** [comment]
Hi guys,

Logged in via browser and confirmed a few times with a code sent to my email. Also had to click 'this was me' when asked about the bot attempted login, but whatever I do, whenever I run the bot again I get the "Login error! Connection error!".

Anyone have an example of a proxy I can try to use or how I can set one up? Much appreciated.

**Comment by drallcom3** [comment]
I have the same problem. Proxy/VPN didn't change anything. Error log is empty.

I did a few test runs on my (quite old) test account this morning. Everything worked perfectly. It was maybe an hour in total.
Now in the afternoon I get that error, my profile isn't available in the browser and when logging in I have to provide a phone number. Has my account maybe been banned or flagged?

**Comment by LopesX** [comment]
Same here! :(

**Comment by vansprosk8** [comment]
the same problem!

**Comment by TRys8** [comment]
I have the same issue.  Using private proxies.  Have even tried changing up the proxy (i.e. swap out my proxies for new proxies).  But I run three accounts on a proxy, and one of them still works.  I think it's possible the accounts have been flagged due to the suspicious activity.  I had tested logging into the browser and clicking "this was me."  It worked for one of them, but the others I never logged into the browser first.  Perhaps logging into the browser with the proxy before ever and authenticating with the security code before ever running the bot prevents Instagram from flagging the account.  Hypothesis is if you don't login first and authenticate, then Instagram flags the account when running through thr API.  Will report back if I can get the other accounts working.  Both accounts that get the error still don't work after I waited for 1 day, so it's not clear to me why some accounts work with the private proxies I have and others do not.

**Comment by vansprosk8** [comment]
I use proxy, from USA ip it did not work. Then I used Swiss ip and now it works! What is interesting, I didn't get the security code in the both cases. After login in, I switched off the proxy (the bot was launched) and used my local ip, and the bot is still working...

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
