### ISSUE TITLE
NOT LIKED 400

### ISSUE THREAD

**Issue by juanrojasm** [instabot-py/instabot.py#1256]
Hi, something special is happening to me, I have always used instabot with 7 accounts, today I decided to add two new ones, and now they all say NOT LIKED 400.
That could be happening?
Thank you

**Comment by dexs99** [comment]
400 error would mean that instagram banned you, if you have this error on all your account probably you are doing this work with 1 IP address (not good idea), if not this just enter to instagram site on your browser and see what instagram says you. BR

**Comment by massy384** [comment]
Hello,
I have same issue, is there a way to work with same pc with differents IP address or other way to avoid this issue using the same pc?
Thank you guys!

**Comment by dexs99** [comment]
@massy384 you can use a proxy for this...

**Comment by juanrojasm** [comment]
Hello, how can I use several IP? I tried proxy but I did not know how to do it.

**Comment by dexs99** [comment]
You need to put the proxy config inside your code in the format 
- user:password@host:port        #if you have a proxy with username and password
- host:port         #if you have an open proxy

![proxy](https://user-images.githubusercontent.com/38705585/39434968-6ee1412a-4c9a-11e8-8f9d-441a6c0927d5.png)

You can use public proxy, google "free proxy list" if you want a free proxy, better if you take one that is from your country and supports https! 

But i recommend using private proxies!

Have a nice day!

**Comment by massy384** [comment]
@dexs99 Thank you for your help!
so if I have differents account, How I have to configure it? same proxy port for each account? and what about IP address related to the proxy port? 
Thank you !!

**Comment by juanrojasm** [comment]
Im trying wit proxyand instabot told me Login error! Connection error! :(

**Comment by juanrojasm** [comment]
From the cell phone I confirm that it's me from another location, and yet he keeps saying that

**Comment by dexs99** [comment]
Hi @juanrojasm, it is very likely that it is because you are connecting from an ip that you have never used, to jump this connection error enter your instagram from a pc without proxy and you will notice if it says "suspicious login attempt", just confirm that it is you and then return to your script and execute it again. Good luck!

**Comment by dexs99** [comment]
sorry i see your last message now, so try this, on your script leave proxy with empty info " proxy='' " on "instabot.py" try to uncomment the line 211 and change the "proxyip:proxyport" with your proxy, then re-run the script
![captura de pantalla de 2018-04-30 19-06-08](https://user-images.githubusercontent.com/38705585/39440067-08c0c766-4caa-11e8-986b-6231f548a1d5.png)

**Comment by dexs99** [comment]
@massy384 it would be better to use different proxy for each account, for example

47.254.29.17:80 

this is a proxy that needs to use the port 80 to connect (the part after the ":" is the port) and is defined by the proxy configuration.
search on google for more info!
Good luck!

**Comment by massy384** [comment]
@dexs99 thanks for your help.
I changed line 211 and in instabot.py and also proxy in botmassi.py but it give following error:
![error](https://user-images.githubusercontent.com/38461753/39442625-26e28240-4cb2-11e8-822f-82ae2c7b31a1.jpg)

**Comment by massy384** [comment]
@dexs99 sure!
![proxy](https://user-images.githubusercontent.com/38461753/39443479-0d4fb9f8-4cb5-11e8-9e9f-d84871712985.jpg)

**Comment by dexs99** [comment]
@massy384 ok i see the error, just erase the space that is at the beginning of the line 211, it needs to be to the same level of the others self! then save and try again!

**Comment by juanrojasm** [comment]
No run :(
![image](https://user-images.githubusercontent.com/37377126/39444876-c58a3566-4c7e-11e8-83c3-94fc60e04188.png)

I dont know what happen 
![image](https://user-images.githubusercontent.com/37377126/39444892-d656db06-4c7e-11e8-9e43-3e43797500ca.png)

**Comment by massy384** [comment]
@dexs99 now I have Login error! Connection error!
From the same pc I confirmed that it's me from another location, run again the script but still same error :(

**Comment by dexs99** [comment]
@juanrojasm giù need to delete the # from the beginning of the row self.s.proxies Delete the "# " save and re run

**Comment by dexs99** [comment]
@Massy384 try with another proxy?

**Comment by juanrojasm** [comment]
Not yet..
![image](https://user-images.githubusercontent.com/37377126/39446442-2764901a-4c84-11e8-95c0-935c4b82a04b.png)

![image](https://user-images.githubusercontent.com/37377126/39446462-365708be-4c84-11e8-80bc-b8d76331b137.png)

**Comment by massy384** [comment]
tried many different proxy but still same error
is there anyone is using proxy with success? 
Please help !
Thanks

**Comment by dexs99** [comment]
@juanrojasm @massy384 the configuration is ok, the problem is with the proxies, i make a test with 20 free proxies that i found on the internet and none has worked, I work with a private proxy, that's why it works for me. So you need to buy a private proxy for this, with a single proxy for example I work with 3 different accounts (I would not use more accounts with a single proxy). I hope you are lucky!

**Comment by massy384** [comment]
@dexs99 I bought a private proxy, initially it seem to work good, after 2-3 minute when it try to like get not liked:400. I set like like_per day : 1200, is it ok?
![notliked](https://user-images.githubusercontent.com/38461753/39464574-8b52856a-4d1e-11e8-845b-33b0ef26178d.jpg)

**Comment by dexs99** [comment]
seems like the new rate limits are **200 calls per user per hour**, so maybe you have to change that value by half or something like that... try with 900 and notice what happens after 1 hour that you have executed the script... if you have that error again change the value again in less....

**Comment by massy384** [comment]
@dexs99 thanks again for your help,
I changed to 800 like per day because at 900 I get the error, it start good but in 2-3 minutes it stop with same error: not Liked: 400
following my actual configuration:
![bot_conf](https://user-images.githubusercontent.com/38461753/39470325-5479fbee-4d3d-11e8-9f81-15b5b384e280.jpg)
I am using the bot for 3 account with proxy same configuration like the image and I have same error for each
also on the same pc I am using the bot for 4 account without proxy with no error

I don't understaind why I have the error with proxy

**Comment by dexs99** [comment]
@massy384 try to less the number of likes more. Try with 200 and see what happens. If the problem is not present after this change then up the value to 300... I mean you need to try to catch the right value... just try... I read that is better to use 1 proxy for each account. You use 1 proxy for 3 accounts. Just look for the right balance...

**Comment by massy384** [comment]
I come back after many test. 
it seems not depending from how many like I set. I run the bot for the same account from another pc without proxy and work with no error. maybe the error was because the proxy  is not close to my place: I am in Italy and proxy was from Germany. 
Do you guys has other idea?

**Comment by juanrojasm** [comment]
Hi, with proxy I can´t.
it always asks me to verify from the app. After checking I try again and it does not work either

**Comment by dexs99** [comment]
@juanrojasm maybe that proxy is banned? what proxy are you using? private or free? if you want to use free you need to search one that can be use because unfortunately the free proxy are ban faster by instagram.

**Comment by Kaybkac** [comment]
I have the same problem, my dummy accounts keep getting blocked. What I tried was create a hashtag that's never been used so that it can only like 1 picture and then upload a pic in one dummy account and run the other with that one hashtag, but it's still getting blocked

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
