### ISSUE TITLE
Max retries exceeded with url INSTAGRAM.com

### ISSUE THREAD

**Issue by deyvid5** [instabot-py/instabot.py#1284]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x ] 3.x

## Description of your issue

It was working fine untill I've restarted my computer. How can I reset this connectivity couter again?
Any try of opening this script results with an error from topis. Max retries exceeded with url.....[]

**Comment by mehrdadmms** [comment]
@deyvid5 
hi, how did you make it work again i have this problem : 
Except on SendRequest (wait 60 sec and resend): HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/si/fetch_headers/?challenge_type=signup&guid=a21cb47926a6430886d44459d6945aa4 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa017532b70>: Failed to establish a new connection: [Errno 111] Connection refused',))
