### ISSUE TITLE
Connection Error - Proxy

### ISSUE THREAD

**Issue by TRys8** [instabot-py/instabot.py#1298]
I have read through proxy issue #71 #821 #578 and a few others.  However, none of those posts have helped me solve my issue.  I am running more than 5 user accounts and would like to use a proxy, because Instagram is throttling my ability to Like.  I assume it picks up on my IP address, because if I use 5 or less accounts it seems to be ok.  To use a proxy, I go to free-proxy-list.net.  I am able to change my network settings on Windows 7 and use most of the proxies on this site to access Instagram through my browser.  A few are detected by Instagram as unsecure, but for the most part they work through my browser.

After finding proxies that work through my browser, I try to set the proxy variable in example.py.  I downloaded this repository on 5/20/18, so it should include all of the bug fixes relating to proxy.  I go to example.py, and I set the proxy variable to something like:

'proxy='47.206.51.67:8080',

This specific proxy has worked for me when modifying my LAN settings in Windows and logging in through my browser.

I then get this error when running "python example.py":

`26.05.2018_15:26 Login error! Connection error!
26.05.2018_15:26 Removing already liked medias..
26.05.2018_15:26 Trying to unfollow #1:
26.05.2018_15:26 Removing already liked medias..`

Do I need to modify any code other than the proxy variable in example.py?   Or is the issue due to the fact that I'm using the free-proxy-list.net site to find my proxy?  Again, these proxies work for me when I change my LAN settings in Windows 7 and then sign into Instagram through my browser, so I don't understand why I get the connection error when running through the same proxy server in instabot.py

Any help is much appreciated!

**Comment by TRys8** [comment]
my issue was answered here: #1256

I needed to buy my own proxy servers, as the free proxy servers seem to be noticed for some reason by Instragram.  Also though, Instagram recognizes that someone is trying to log in from another geographic location, so I needed to authorize the attempt by actually logging into the account through my phone.

**Comment by markeli1** [comment]
Thank you for your free instabot.py, it was really useful.
Can you please help me? I select proxy as it is required (for example proxy='12.12.12.12:2323'). Proxy do work, I have already checked. But bot still cannot see the proxy because instagram account sees my IP again.
Thank you in advance

**Comment by roshan6040** [comment]
Hi there,  Please advise on my mistake using an open proxy.
  # if you need proxy make something like this:
        self.s.proxies = {"https" : "http://159.89.184.107:80"}
        # by @ageorgios
        if proxy != "":
            proxies = {
                'http': 'http://' + proxy,
                'https': 'http://' + proxy,

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\xxxxx\Desktop\instabot.py-master\src\instabot.py", line 234, in __init__
    self.login()
  File "C:\Users\xxxxx\Desktop\instabot.py-master\src\instabot.py", line 284, in login
    r = self.s.get(self.url)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 502, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001CCB1425
630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)))
