### ISSUE TITLE
Not Liked: 400 error on all accounts. Like is working on web instagram and mobile app

### ISSUE THREAD

**Issue by danifki** [instabot-py/instabot.py#1378]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. 

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [ ] 3.x

## Description of your issue
I've been running 6 bots on local IP (home) and today all of them started the Not Liked: 400 error. All at the same time. Follow/unfollow still working on all accounts.
I can like photos if i login on web instagram and mobile. Like is still working if not using the bot.
What can i do?

**Comment by Hiutaky** [comment]
First of all i can say that you can run at least 2/3 bot per IP, since that instagram will ban all your account. If you set your bots with aggressive settings ( more than 1500 likes per days, more that x comments per days etc) it will block your Action and return that Error. So, try to set less aggressive settings, and use some proxy to stay secure that instagram will not ban you.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
