### ISSUE TITLE
Unfollow isnt working

### ISSUE THREAD

**Issue by joshi2000** [instabot-py/instabot.py#1527]
I tried to find other issues that already fixed the Problem but none of them had working Solutions or were up to date. The Problem i am having is that the Bot wont unfollow the people, otherwise it works perfectly and im thankful for the work. It always try's to unfollow #1. Any idea what could cause/fix it ?

here is a transcript of my Bot: 

24.08.2018_11:20 Trying to like media: 1852862192061634634
24.08.2018_11:20 Liked: 1852862192061634634. Like #30.
**24.08.2018_11:20 Trying to unfollow #1:** 
24.08.2018_11:20 Getting user info : lgbt_flops_uwu
24.08.2018_11:21 Trying to like media: 1852869829988473223
24.08.2018_11:21 Liked: 1852869829988473223. Like #31.
24.08.2018_11:22 Trying to follow: 8469505599
24.08.2018_11:22 Followed: 8469505599 #12.
**24.08.2018_11:22 Trying to unfollow #1:** 
24.08.2018_11:22 Getting user info : tatianasoash
24.08.2018_11:23 Trying to like media: 1852869792374240408
24.08.2018_11:23 Liked: 1852869792374240408. Like #32.
24.08.2018_11:26 Trying to like media: 1852869738537305302
24.08.2018_11:26 Trying to unfollow #1: 
24.08.2018_11:26 Getting user info : ch1cktender
24.08.2018_11:26 Trying to like media: 1852869448165712593
24.08.2018_11:26 Liked: 1852869448165712593. Like #33.
24.08.2018_11:27 Trying to follow: 7301748560
24.08.2018_11:27 Followed: 7301748560 #13.
24.08.2018_11:28 Trying to like media: 1852869789557432826
24.08.2018_11:28 Liked: 1852869789557432826. Like #34.
24.08.2018_11:29 Trying to unfollow #1: 
24.08.2018_11:29 Getting user info : redhotchilememes
24.08.2018_11:29 Trying to like media: 1852869770563677299
24.08.2018_11:29 Liked: 1852869770563677299. Like #35.
24.08.2018_11:31 Trying to like media: 1852869769231311392
24.08.2018_11:31 Liked: 1852869769231311392. Like #36.
**24.08.2018_11:31 Trying to unfollow #1:** 
24.08.2018_11:31 Getting user info : matt.the.spicy.one.mp4
24.08.2018_11:32 Trying to follow: 7030125111
24.08.2018_11:32 Followed: 7030125111 #14.
24.08.2018_11:32 Trying to like media: 1852869756590213734
24.08.2018_11:32 Liked: 1852869756590213734. Like #37.
**24.08.2018_11:33 Trying to unfollow #1:**

**Comment by fedex03** [comment]
@joshi2000  I opened the same issue yesterday (#1520 )

**Comment by joshi2000** [comment]
Thank you, no one has found a solution so far, right ?

**Comment by fedex03** [comment]
@joshi2000 I think no.
I'm looking for another solution to unfollow people since also bot mode 5 doesn't work.

At the moment I disabled the people following in orde to collect to many following

**Comment by juguntert** [comment]
I just found out that once I cut the bot with ctrl+c it starts the unfollows

**Comment by fedex03** [comment]
@juguntert  Oh really?
Did you modify the bot code?

**Comment by juguntert** [comment]
no... I'm thinking it's already there somewhere I was just stopping it so I could make a few changes to the comment settings

**Comment by juguntert** [comment]
@fedex03 

To be honest, I'm not exactly sure. I had a 403 error that I fixed with this change to the src instabot.py file from issue #1498 . [https://github.com/instabot-py/instabot.py/pull/1498#issuecomment-414754744](here)

After running the bot for a few minutes I realized it wasnt unfollowing so I asked a friend of mine to teach me how to stop it (ctrl C) - I'm on a mac and had never run the terminal before.... - so I could look at the code and figure out how to fix it without messing the whole process up (I'm reeeeeally new to all this python thing)

And thats when I got this:

> 

24.08.2018_19:14 Getting user info : maedaanasofia
**^CTraceback (most recent call last):**
  File "/Users/juguntert/Desktop/instabot.py-fix-login_error/src/instabot.py", line 868, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+show_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "corujando.py", line 91, in <module>
    bot.new_auto_mod()
  File "/Users/juguntert/Desktop/instabot.py-fix-login_error/src/instabot.py", line 721, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "/Users/juguntert/Desktop/instabot.py-fix-login_error/src/instabot.py", line 782, in new_auto_mod_unfollow
    self.auto_unfollow()
  File "/Users/juguntert/Desktop/instabot.py-fix-login_error/src/instabot.py", line 928, in auto_unfollow
    time.sleep(3)
KeyboardInterrupt
24.08.2018_19:14 Trying to unfollow: 1443183146
24.08.2018_19:14 Unfollow: 1443183146 #1 of 92.
24.08.2018_19:14 Pausing for 19 seconds... 1 of 92
24.08.2018_19:15 Trying to unfollow: 593927539
24.08.2018_19:15 Unfollow: 593927539 #2 of 92.


So now I understand that with this src instabot.py fix my bot only unfollows when I shut it down at the end of the day...
Hope this helps!

**Comment by mactrash** [comment]
This issue have been for a long time, but never have official answer... can author give a clear explain  of how the unfollow work?

**Comment by erikpi** [comment]
Doesn't work for me either.

**Comment by fedex03** [comment]
Hi @erikpi, How did you fix it? Did you followed #1503 ?

Thanks

**Comment by fillipemontenegro** [comment]
Please check #1520 

I posted what I believe is a solution. It's working fine for me now.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
