### ISSUE TITLE
"We Noticed a New Login, ..." We noticed a login from a device you don't usually use.

### ISSUE THREAD

**Issue by scotsfloki** [instabot-py/instabot.py#1582]
Hello everyone, I'm getting this email every time I run the bot..
Is it fine or I should be worried?

**Comment by TutOsirisOm** [comment]
It's fine.

**Comment by scotsfloki** [comment]
Ok, thank you for your answer. I had doubts because I used the bot for months but I started to get these messages only a few weeks ago.

**Comment by TutOsirisOm** [comment]
Probably just an update with Instagram, if you really wanted to try and mess with it you could look at changing the headers around... But you should be good, I get that message countless times a day and have no issues. You'll usually know when your account is at risk because Instagram will often give you a couple phone verifications first.
