### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by cullenOG** [instabot-py/instabot.py#1583]
![screenshot 9](https://user-images.githubusercontent.com/43103918/45260849-8bc30100-b3b7-11e8-83b7-b3cedcc4770d.png)

First time trying to run the bot, and I get this error. I am using python 3.6.3

**Comment by cullenOG** [comment]
Thanks for the help, but I searched on google and nothing came up. Any other suggestions?

**Comment by MSkylark** [comment]
Everything went well for the last 2 months but today got the same error and can not find a fix anywhere.

**Comment by marcusagm** [comment]
You can fix it change the file userinfo.py on line 42
form
`json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')`
to
`json_info = json.loads(re.search('{"activity.+probably_has_app', info.text, re.DOTALL).group(0)+'":""}')`
The error occurre because it is not possible to search the json information, probaly because some change in the code.

**Comment by AustinDings** [comment]
@marcusagm I followed your advice and can now log in, but am getting 403 error on repeat. Any tips on what to do about that?

**Comment by marcusagm** [comment]
Nice!
But beware, Instagram has a AI to identify a non human user.
The 403 error is a blocking for some features. Probably your configurations is too abusives. Try to make less actions in one day and define a time to start and finish the execute. Like 10am to 6pm to simulate a human.
To verify that your account is blocking actions, try to make this on cellphone, if you receive an alert, wait a few days to normalize.
The age of account maybe is also important to define the actions limit rate.
