### ISSUE TITLE
follow user follower Config

### ISSUE THREAD

**Issue by Darkomandos** [instabot-py/instabot.py#1862]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

Hello everyone how can i config to follow the followers from a user and the number to follow (ex: follow_user_followers(['user'], follow=10). I'm trying to config this but i'm not find anything that does this. anyone can help me?

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by pablo3600** [comment]
better take and do it yourself because for the results that will give you the bot that continually throws errors lose time and the same would have gotten yourself doing your follow unfollow with your finger the bot is a crap if not with time you will give me the reason over normalmene the people who follow the basis of hagstags are users to make bulk as they neither interact with your content or are from countries that the same for the purpose you want do not serve you more than to fatten your list of followers, over there are people that is so stupid that they will just accept the request and it does not start to follow you

**Comment by dimisdas** [comment]
This isn't supported in the current version of InstaBot. Feel free to open a feature request issue. Thanks!
