### ISSUE TITLE
unfollow_recent_feed=True is unfollowing active people that do follow the bot-account

### ISSUE THREAD

**Issue by martinlombana** [instabot-py/instabot.py#1981]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [ x] Linux Ubuntu
- [ ] Android (include terminal)

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.6.7
```

#### Pip Version?
```
pip 19.0.1
```

#### Description of your issue

With unfollow_recent_feed = True (by default), I can confirm that the bot is populating the database with users that:

- Were following me
- I was following them
- They are active (not ghost users).
- They like all the media I post

**And unfollowing them as well.** 

So, this is either a bug with this parameter/feature or there is something weird. I detected this because I noticed that the account stopped following people that I had followed.

This is not a new bug. This has hapenned since several releases during the last month, and I can confirm it happened yesterday with code from yesterday and the "example.py" from yesterday.

@dimisdas, I did follow all the steps and did a throrough investigation of this issue. That is why I am reopening it. 

So unless there is something in the criteria that is causing this behaviour (that by the way, in your code you only specify that it unfollows people from recent feed that "do not follow you")... that feature has a bug. 

I didn't open this bug without doing hours and hours of testing, during the pasts weeks and yesterday with the most recent code/clean database and code from example.py. 

I know, @dimisdas,  that if I set it to False, I will not have this behaviour. However, it is broken, as "per definition" (unless the documentation is wrong) the bot should NOT unfollow someone from RECENT FEED that follow you.

As you state in the docs:

```
unfollow_recent_feed | bool | If enabled, will populate database with users from recent feed and unfollow if they meet the conditions. Disable if you only want the bot to unfollow people it has previously followed. | True
```

And in the comment in "example.py":

```
unfollow_recent_feed=True,  # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
```

So, there is something wrong. Now, if you care to investigate this or not, that is another question. I agree that my initial issue didn't point out at the fact that the accounts that it unfollowed were following me. : 
https://github.com/instabot-py/instabot.py/issues/1979

Which would have led, maybe, to another response from you, @dimisdas , as you would have identified the bug to be related to this setting and not the general follow/unfollow procedure. 

I tried to answer that, but you closed the issue. 

As you see, if you read all this issue, I did not write this lightly, as you seem to suggest. Nor I am trying to make anyone loose their time, as you explicitly wrote in the above mentioned issue. I am just trying to contribute to fix issues and make this tool better. 

Best regards, 

```
No errors.
```

#### Config

```
bot = InstaBot(
	database_name='_database.db',
	login="*****",
	password="******",
	like_per_day=1000,
	comments_per_day=0,
	tag_list=["cute", "love"],
	tag_blacklist=["sex", "sexy", "nude"],
	user_blacklist={},
	max_like_for_one_tag=50,
	follow_per_day=300,
	follow_time=3 * 60 * 60,  # 3 days
	unfollow_per_day=300,
	unlike_per_day=0,
	time_till_unlike=3 * 24 * 60 * 60,  # 3 days
	unfollow_break_min=15,
	unfollow_break_max=30,
	user_max_follow=0,
	user_min_follow=0,
	log_mod=0,
	proxy=""
)

bot.mainloop()
```

**Comment by dimisdas** [comment]
I appreciate that you made the effort to reopen this issue properly. I have read the issue in full.

To clarify, unfollow_recent_feed when set to True (default) will insert into the database people from your recent feed (that you are following). 

![screenshot 2019-02-13 at 14 07 45](https://user-images.githubusercontent.com/1391441/52710739-be8da880-2f98-11e9-8c42-26ec4793850c.jpg)

When the new_auto_mod_unfollow's interval ticks, it will randomly select a person from the database. The database is also populated with people the bot has followed. So it's a mixed pool of users.

I see in your posted configuration you haven't set unfollow_recent_feed to False yet. Given the explanation above, please try setting it to False and then delete the .db file.

The bot **will take some time** before it unfollows someone again, which is what struck as me odd in your previous issue. There's a hardcoded requirement of 20 accounts in the DB before it can unfollow again, plus the `follow_time=3 * 60 * 60` you have in your config. How is it possible that you tested this?

Given that your `follow_per_day=300` it would take 288 seconds * 20 users = 5760 (96 minutes), plus 3 hours (3 * 60 * 60).

![screenshot 2019-02-13 at 14 11 01](https://user-images.githubusercontent.com/1391441/52711056-8aff4e00-2f99-11e9-8ce9-3cea2765a7bb.jpg)

If unfollow_recent_feed fixes your issue, please let me know and I will take a look over the documentation to see if there are any mishaps to correct. 

Otherwise, should it persist, it would be of great help if you could you please post the relevant log with the unfollow criteria analysis. Include an example of a username it unfollowed (if you wish, you may email it to me in private).

**Comment by dimisdas** [comment]
I hope you also now understand how unfollow_recent_feed works. 

> I know, @dimisdas, that if I set it to False, I will not have this behaviour. However, it is broken, as "per definition" (unless the documentation is wrong) the bot should NOT unfollow someone from RECENT FEED that follow you.

The definition seems to be correct. What's confusing you exactly?

```
unfollow_recent_feed | bool | If enabled, will populate database with users from recent feed and unfollow if they meet the conditions. Disable if you only want the bot to unfollow people it has previously followed. | True
```

**Comment by martinlombana** [comment]
Okey, 

Yes, this is my current config, which I set in order to not have any unfollow. I just changed it recently after I saw I was stopping from following people that followed me. 

But with those settings, it stills adds to the database, people that followed me and were active. 

And I haven't set the unfollow_recent_feed in this issue, because, as you said, this will probably remove that problem for me, but, as I pointed out, this means the problem is whithin that feature. Specially if it should unfollow only people that are not following you. 

As you pointed out:

``` 
When the new_auto_mod_unfollow's interval ticks, it will randomly select a person from the database. The database is also populated with people the bot has followed. So it's a mixed pool of users.
```

There is the problem. This is uncompatible with this explanation:

```
unfollow_recent_feed=True,  # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
```

Because this last statement is false, I believe. If the bot adds people to the database from recent feed that you are following (without any check to avoid adding it to the database if that person is follwing you), this means that it is going to add people to the database that potentially follow you.

And then, when they get randomly selected for unfollow, some of those people that the bot will unfollow... will be people that follow you. 

That is what I was experiencing.

**Comment by dimisdas** [comment]
> Because this last statement is false, I believe. If the bot adds people to the database from recent feed that you are following (without any check to avoid adding it to the database if that person is follwing you), this means that it is going to add people to the database that are following you NOW.

The bot performs a check before unfollowing, and not when inserting into the DB.

**Comment by martinlombana** [comment]
So the bot never unfollows accounts that are following you?

(Because that is happening. And I can understand it for “new accounts”.)


-- 

___________________________________

*Martín Lombana *

*TODOLOGIC.COM <http://TODOLOGIC.COM> *

*+34 633 63 02 35  |   *+34 946 759 137

*INSTAGRAM *→* @ <https://instagram.com/todologic>TODOLOGIC
<https://instagram.com/todologic>*

**Comment by dimisdas** [comment]
Just to clarify,

unfollow_recent_feed does not unfollow anyone itself. The name might have caused some confusion.

It will only populate the database with people from recent feed.

The criteria for unfollowing are the same and are currently hard-coded. They will be modular in the next version with their own parameters.

https://github.com/instabot-py/instabot.py/blob/bbf58ed24dfcaeb989241dd6d98e7644f9a56f64/src/instabot.py#L1448-L1482

If you turn unfollow_recent_feed off (set to False), then the .db will only be inserted with users the bot has followed itself. In case you were already following them, then they shouldn't be added in the database because the follow will have failed.

**Comment by martinlombana** [comment]
I see now what is happening:

The conditions specified there (and not in the readme.md) are more complex than just "unfollows only if it doesn't follow you".

And I experienced problems with accounts being flagged as "Selebgram" or "Fake Account", due to those filters... which are actually  real accounts. 

One of the accounts, that I know personally has 22k followers... and follows 1890 people. Which makes it being flagged as a Selebgram. Another account is following 9000 people but has only 200 followers, which is being flagged as a fake account. 

I don't think there is a way, now, without un-hardcoding it, to remove those checks, right?
(I didn't find it through the code, at least, or there is no setting in the parameters).

**Comment by dimisdas** [comment]
Nope, there isn't. I actually inherited that part of the code, which existed way before I joined this project. 

It will be rewritten soon though.

**Comment by martinlombana** [comment]
Ok. Because there is the culprit, I am sure:

This condition:

```
if (
                self.is_selebgram is not False
                or self.is_fake_account is not False
                or self.is_active_user is not True
                or self.is_follower is not True
            ):
```

to 

```
if (
                self.is_selebgram is not False
                or self.is_fake_account is not False
                or self.is_active_user is not True
                or self.is_follower is not True
            ):
```

Could be changed (for now) to:

```
			if (
					self.is_follower is False and (self.is_selebgram is not False or self.is_fake_account is not False or self.is_active_user is not True)
			):
				new_auto_mod_unfollow2(self)
				try:
					del self.media_on_feed[chooser]
				except:
					self.media_on_feed = []

```
This would avoid unfollowing real celebrity accounts that follow you (if the user doesn't want that to happen).

**Comment by Brcalvo** [comment]
I had the same issue. Basically I eliminated all the other options and left only:

"self.is_selebgram self.is_follower is not True"

This will make sure that the bot doesn´t unfollow anyone who follows me, no matter their follows or follower ratio. 

The problem is that the bot, for some reason, only extracts from the DB users that are following me, so at the end of the day it doesn´t unfollow anyone. Any idea why this could happen?

Thanks!

**Comment by dimisdas** [comment]
The unfollow conditions have been added in the latest version.  :)
