### ISSUE TITLE
A question about the unfollow_not_following function.

### ISSUE THREAD

**Issue by rafaelsousa221** [instabot-py/instabot.py#2023]
it unfollows all of the users that do not follow me or just the ones that the bot follow and they do not follow back?

**Comment by dimisdas** [comment]
If `unfollow_recent_feed` is set to True (default) it will also unfollow people from your recent feed that match the unfollow criteria.

Otherwise, if `unfollow_recent_feed=False` and `unfollow_not_following=True`, it unfollow people that the bot has followed and have not followed you back within the `follow_time` time window.
