### ISSUE TITLE
unfollow_everyone not working 

### ISSUE THREAD

**Issue by olaims** [instabot-py/instabot.py#2127]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour) 
- [ ] Android (include terminal)

raspberrypi 3 with last Raspbian version

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.6.3
```

#### Pip Version?
```
pip 19.1 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)
```

#### Description of your issue

```
I try to use the unfollow_everyone but the bot just shows all the time "Looks like there is nobody to unfollow"
```

#### Config

```
like_per_day = 812
comments_per_day = 0
max_like_for_one_tag = 57
follow_per_day = 190
follow_time = 36000
unfollow_per_day = 247
tag_list = ["xxxxxxxxxxxx"]
unfollow_everyone = true
unfollow_selebgram = true
unfollow_probably_fake = true
unfollow_inactive = true
unfollow_recent_feed = true
```

**Comment by dimisdas** [comment]
The bot will insert people into database. Since you have unfollow_recent_feed=True, it will insert both people it followed itself and people for your feed.

After follow_time (seconds) has passed since the user was inserted in the database, they will be matched for criteria. In your case, everyone will match and be unfollowed (unfollow_everyone).

If there’s no account inserted into the database that is eligible yet, i.e. (inserted_time + follow_time) < current_time, then you’ll get the message “Looks like there is nobody to unfollow”.

**Comment by olaims** [comment]
@dimisdas  setting the "unfolow_recent_feed" to false would help? because I tried and the same behaviour.

**Comment by dimisdas** [comment]
Reduce follow_time to 0.

**Comment by olaims** [comment]
ok thanks
