### ISSUE TITLE
Action Blocked, any solution to avoir that?

### ISSUE THREAD

**Issue by alaintainguyen** [instabot-py/instabot.py#2496]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [X] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [X] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.4
```

#### Pip Version?
```
19.2.3
```

#### Instabot Version?
```
0.5.19
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [X] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
Any solution to avoid that? 
status code: 400. Reason: {"message": "feedback_required", "spam": true, "feedback_title": "Action Blocked", "feedback_message": "This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/instagram_like_add/", "status": "fail"}
```

#### Config

```
Ensure that you specify the configuration file in the command line.
Ensure that the default file instabot.config.yml contains only common settings if you use multiple accounts.
Include the contents of your config here (instabot-py -c config.yml --dump) (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT

```

**Comment by elvirmuslic** [comment]
Not really. 
I'd like to see the following feature implemented. 
Since instagram takes into account device, usage and similar. 
It would be a **wise** option to implement a fake action seeder.

What do I mean? 
Make a human like bot for a few days that will act like a human, just liking and similar and then do actual bot actions, mass follow and such. 

Why?
Instagram takes into account if you just logged from another device and suddenly start doing mass like/follow or similar. It takes a few days until instagram recognizes and starts trusting the new device.

Tehnical -
It seems that Instagram has a **Trust** **Score** of the device amongst other things. Implement a feature i.e. script that will roam and do everyday tasks.
- Scroll
- Like few pages 
- Stop at random points 
- Swipe to see more (in album) 

We could skip this step if we could emulate **OUR own devices** that we use regularly and it wouldn't it would automatically inherit our **Trust Factor**.
