### ISSUE TITLE
Continuous follow-unfollow of same accounts + unfollow accounts even if unfollow_per_day=0

### ISSUE THREAD

**Issue by AdrianaVecc** [instabot-py/instabot.py#566]
Hi. The script never checks if condition "is following" is true. As a result, it finds the same accounts over and over again.

Even worse, I have set the number of daily unfollows to 0 (unfollow_per_day=0), but it unfollows accounts I already follow anyway. The reason being because it doesn't check the condition above. So by trying to follow those accounts, it actually unfollow them (since it's the same button).

Proposed fix: introduce condition "is following" and exclude accounts if true

**Comment by lsdsssc** [comment]
I use the unfollow feature on the original instagram bot here on github.

My bot also follow same ID number multiple times so if i follow 500 people it only follows maybe 200.

The only thing that helps me is only using hashtag that has 2 million plus results, because it usually follows same ID number after "Get media id by tag: cute"

**PLEASE ADD NEW FEATURE**

IF: 
    ID_number_already_followed
ELSE:   
          Follow_Next_ID_Number

**Comment by ChipWolf** [comment]
#386
