### ISSUE TITLE
trying to use instabot on multiple accs , problem 

### ISSUE THREAD

**Issue by newdjpower** [instabot-py/instabot.py#597]
hi , i using AWS to run instabot py . Is working fine , if i open 2 maybe 3 accounts ,but when i try to run 10 accs , in few minutes i get the error not liked 400 .all accounts have proxy .i verrified the accounts on windows and no accounts get banned or asked if it was me , and i can like and follow people .so what can be the problem ? 
![bot](https://user-images.githubusercontent.com/29121588/27196622-829eddf6-520b-11e7-9a69-a12cfb5bc5c3.jpg)

**Comment by dcanones** [comment]
Are you using the same proxy for all accounts? 400 error means Instagram Shadow-Ban  caused by spammy behavior and since last month or so is becoming very common... it also takes into account previous activity of the account, it is: if you automate a new account with 0 followers, 0 activity/ average likes per day, IG founds suspicious an activity surge of 1000 likes per day or so. My recommendations are:

- Dedicated proxy per automated account.
- Starting with slow activity (500 likes or so...).

PS: If you know how to use AWS (as you said before), switch to a EC2 linux instance or Lightsail VPS. Its much cheaper and efficient than a Windows Virtual Desktop.

**Comment by amirsyazi** [comment]
try to keep 1 proxy 3 to 5 acc max.
