### ISSUE TITLE
Autorestart when stopped

### ISSUE THREAD

**Issue by focamonca** [instabot-py/instabot.py#598]
I have 2 istances of instabot running on a raspberry pi zero w.
Sometimes it stops (even on win 10), randomly, without any reason.
Is it possible to embed a script to autorestart it?

thanks

**Comment by focamonca** [comment]
![Screenshot ](https://i.imgur.com/j4keV4L.jpg)

This is what happened me last night.. 
I just want to know why and why it happened  

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by focamonca** [comment]
And again 


![Screen ](http://i.imgur.com/Kdvtu6w.jpg)

**Comment by focamonca** [comment]
WTH!

http://imgur.com/a/zj8q5

**Comment by tunidev** [comment]
The problem occurs because because there is a problem in the method that checks if the comments exists `self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:` I have fix it by just removing the check in      instabot.py line 636 replace : 

          `and len(self.media_by_tag) > 0 \
and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:`

by 

`and len(self.media_by_tag) > 0:`

**Comment by AdrianaVecc** [comment]
Same error, but this didn't solve it for me :(

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
