### ISSUE TITLE
How to just UNFOLLOW THE USER that BOT HAS BEEN FOLLOWED without using "unfollow_whitelist"

### ISSUE THREAD

**Issue by zhen737** [instabot-py/instabot.py#630]
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**
^ (I've searched around issues, seems everyone going smooth on this features ;/ )

Hi all, below are my currently settings, it has been running pretty well on mode 0, the only thing is I do not know how do I unfollow people which bot has been followed after 12 hours. (I'm not sure if "bot_follow_list" is working. Therefor I'm still using "unfollow_whitelist", which is kinda annoying whenever I follow my real life friend I need to manually add their username into my whitelist.)

```
follow_per_day=450,
follow_time=0*60,
unfollow_per_day=450,
unfollow_break_min=15,
unfollow_break_max=30,
log_mod=0,
mode = 0
```

I've tried using without the whitelist on mode 0, the bot going to unfollow everyone, including people that wasn't follow by my bot. How do I do?

**Comment by uuaing** [comment]
That's current desgn, I would say it's an code issue. if you look into the mod 0 for unfollowing, you'll find the unfollowing logics is wrong, it first search in your recently feeds and filter by some conditions to determine if this user need to be unfollowed, then do unfollow, that's why users not followed by bot also can be unfollowed.

**Comment by ChipWolf** [comment]
#386
