### ISSUE TITLE
Not unfollowing - just 15 users, then stops working

### ISSUE THREAD

**Issue by Pheela1** [instabot-py/instabot.py#647]
Hi Guys, I am trying to run mode 5, problem is that it unfollows like 15 users and then it just tries to unfollow, but never unfollows. I have even adjusted the limit to 99999 as suggested in other threads.

Basically it looks like this:

 13.07.2017 19:07
Media in recent feed = 24
Trying to unfollow: USER1
NAME : Get media id on recent feed 
 13.07.2017 19:07
Media in recent feed = 24
Trying to unfollow: USER2
NAME : Get media id on recent feed 
 13.07.2017 19:07
Media in recent feed = 24
Trying to unfollow: USER2
NAME : Get media id on recent feed 
 13.07.2017 19:07
Media in recent feed = 24
Trying to unfollow: USER3

does anyone know what to do? I am out of ideas.

**Comment by Pheela1** [comment]
if i wait few minutes, i am able to start it again and unfollow another 15 people.

I dont understand why, there is no limit set for 15 unfollows only

**Comment by Craiting** [comment]
This is a restriction that instagram has implemented on the web api. If you open up the dev tools in chrome and try to unfollow people the requests stop working at 15 then you have to wait a period of time for it to allow unfollows again.

One thing I wanted to do but haven't got around to it yet is use some program like wireshark monitor http requests on a network to figure out what endpoints the mobile app hits to unfollow users because the mobile app doesn't appear to have that restriction.

The web endpoint is: `https://www.instagram.com/web/friendships/48311450/unfollow/`
The android endpoint I don't know what it is yet.

**Comment by ChipWolf** [comment]
@Craiting when you do have a chance, please contribute
