### ISSUE TITLE
Bot signing out after random time spent

### ISSUE THREAD

**Issue by MesCalinez** [instabot-py/instabot.py#698]
Hi,
My bot stops working when trying to unfollow a user. this will happen at random times, I've seen the range of 30 minutes to 7 hours.
I was getting "thread" error with Python 2.7 but after installing Python 3.6.2 It will stop without any error. this is what I got from the log.txt

`Unfollow: 12164599 #20 of 34.
Pausing for 16 seconds... 20 of 34
Logout: likes - 107, follow - 34, unfollow - 20, comments - 33.
Bot work time: 2:42:30.027430
Logout success!
`

**Comment by dv1pr** [comment]
I use python_3.4 and don't have that issue.

**Comment by MesCalinez** [comment]
Thanks @dv1pr . I will try it.

**Comment by wizarduk** [comment]
@dv1pr is yours still fine ?

**Comment by dv1pr** [comment]
@wizarduk mine's fine but I've basically re-built the entire thing from the ground up and added a bunch of new features. I will say if you lose internet connection for any reason it will most definitely cause your bot to bug out. I had to had try/catches to a lot of the features to ignore that because the EC2 servers I'm hosting them on would restart every day (briefly, like for 5-10secs only) and would cause log outs. That was the biggest problem I found when switching to from local machine to remote servers. Also After updating the app I went back to using python2.7. You really have to play around with it to make it work for your situation.

**Comment by wizarduk** [comment]
Sounds good @dv1pr im having better results with another script as this one is way to buggy

**Comment by MesCalinez** [comment]
My script acts a little bit weird! it depends on the user. for some users, it works for more than a week but my user will face bugs in couple hours.
I tried different python versions but no difference.
@wizarduk can you share the new script you've mentioned?

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
