### ISSUE TITLE
Install requirements denied

### ISSUE THREAD

**Issue by Maikivu** [instabot-py/instabot.py#717]
Hi! 
First off all. Thanks for making this incredible bot. I have used it on my mac with no problems for weeks. Im changing over to windows now and couldnt get through the install requirements step. It looks like the request is denied. 

I have tried "pip3 install r- requirements.txt" and also "sudo pip install -r requirements.txt". Someone said that worked for them, but for me it didn´t. Thats why im posting this issue now. Would appreciate any help. Look at the picture. THANKS IN ADVANCE

![20954052_10155463038502184_870759500642052177_n](https://user-images.githubusercontent.com/20546729/29638422-8b4897e4-8857-11e7-9859-fc42b9f7f238.jpg)

**Comment by maelzx** [comment]
The error is about permission. I'm guessing you did not run the cmd as administrator.

Try type CMD, instead of Enter, you right click on CMD and select run as administrator.

Refer here: [denied access program files x86](http://www.tomshardware.com/forum/id-2768485/denied-access-program-files-x86-folder.html)

**Comment by Maikivu** [comment]
Thank you! It worked. Im closing this issue now.
