### ISSUE TITLE
Bot follows only 40 people before logging me out.

### ISSUE THREAD

**Issue by Abzidian** [instabot-py/instabot.py#817]
The bot only follows the first 40 people on the bot.follow command and then logs me out. I have also changed limit = 999999999999999999999999 in follower_protocol.py

bot = InstaBot(
login="**********",
password="*********",
log_mod=0,
follow_time=(60 * 60))

bot.follow('userid1') 
bot.follow('userid2')
.
.
.
bot.follow('useridx')  

Any idea how to increase it from the first 40?
I've also tried removing the first 40 from the list, such that 40 onwards will run, but it just logs me out without doing anything.

**Comment by kanegovaert** [comment]
The bot crashes sometimes caused by unexpected JSON responses from what I have seen debugging the script. I have found a solution so the script can run 24/7

If using Windows just create a new .bat file and insert:

`title Instagram Bot
echo off
color b
cls
echo Starting script for Instagram...
python "path\example.py"
:A
echo Restarting script for bot after 5 minutes...
SLEEP 300
python "path\example.py"
GOTO A`

Whenever the script crashes it pauses for 5 minutes and continues as usual. You can also give the cmd window text different colors if you're running multiple bots.

**Comment by Abzidian** [comment]
Thanks!
