### ISSUE TITLE
Not liked : 400

### ISSUE THREAD

**Issue by ugurozturk** [instabot-py/instabot.py#887]
- [x] Bug

## What OS ?
MAC / Windows / Linux(detail) / Android
## Python Version ?
2x / 3x
## Is it VPS ?
Yes / No

There is a lot of duplicate "not liked 400 error" issues. Use this issue in the future

**Comment by hgic86** [comment]
Hi,

This is stil a bug right? I haven't run it because I think IG is on to me lol

**Comment by ugurozturk** [comment]
It is not a bug, it is something must avoid. There is a lot of reasons to cause it. This issue for "must be avoiding thing lists"

**Comment by hgic86** [comment]
What do you mean "This issue for "must be avoiding thing lists""? Is there a list somewhere?

**Comment by ugurozturk** [comment]
@hgic86 https://github.com/instabot-py/instabot.py/issues/887 created for this purpose

**Comment by kemong** [comment]
Instagram banned Specific Action for a Specific Account on Specific IP.
That's why Instagram give 400 not liked to Account A on IP 123.123.123.123. But Account A can like photos on IP 234.234.234.234.
And also, account B on IP 123.123.123.123 can like any photos as usual.
The solution for now is change your IP or wait until Instagram cancel banning that specific action for specific account on specific Ip.

**Comment by barronlroth** [comment]
@kemong How can one change IP on DigitalOcean linux box?

**Comment by emmemeno** [comment]
Hello!
I've noticed the bot get soft banned (e400) during my off hours (night), maybe IG antiBot system become a little smarter.
Is it possible to set the bot to work only in a default window (ex. from 8am to 11pm local time)?

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Comment by mansProFX** [comment]
Renew IP can fix it?

> ifconfig /renew

 solved my problem.
