### ISSUE TITLE
Verification Loop - Can't login anymore!

### ISSUE THREAD

**Issue by mdrzn** [instabot-py/instabot.py#978]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Running on Debian 7 3.2.78-1

## Python Version?
2 / 3
Python 2.7.3

## Description

Type the description of your issue here.
Getting the verification loop, I try to login from the bot and it fails. Once I login from the mobile app or website, I get the "suspicious login activity" and I even if I click "It was me", the bot can't login on the next try.

```
Include the contents of the error.log here (if applicable).
```

**Comment by carlosisazadotlife** [comment]
Hosting
[X] Are you hosting the bot on a VPS or other Cloud hosting? Yes
      If so; have you tried running the code on your local machine? Not an option. Haven't been able to get it to work on my Mac OS Sierra ver. 10.12.6

Select one:
      Bug
      Feature Request
[X] Technical Help
      Other

Operating System? (include version) ubuntu-xenial-16.04-amd64-server, running on AWS EC2 Instance

Python Version?
Python 2.7.12

Description
Type the description of your issue here.
Getting the verification loop, I try to login from the bot and it fails. Once I login from the mobile app or website, I get the "suspicious login activity" and I even if I click "It was me", the bot can't login on the next try. It was working just fine this morning

**Comment by digital-bloom** [comment]
#980

**Comment by mdrzn** [comment]
So, it happened 5 days ago for the first time. I stopped trying to login for 24hrs, and after that I could login normally.
Now, it happened again (verification loop). I waited 12hrs and tried to login again, still error.
What is causing it? Is there any way to use a proxy in this python script?

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
